#Start developing with CI

stages:
  - build 
  - test

build:
  stage: build 
  image:  openjdk:8-jdk-slim
  artifacts:
          paths: 
            - /tmp
before_script:
  - docker info            
  script:
        - echo "Building the app"

#test: 
#  stage: test 
#  image: existdb/existdb:release 
#  dependencies:
#    - build  
#  script:
#        - echo "Testing the app"
