#Start developing with CI

stages:
  - build 
#  - test
before_script:
  - docker info    
build:
  stage: build 
  image:  openjdk:8-jdk-slim
  artifacts:
          paths: 
            - /tmp
        
  script:
        - echo "Building the app"

#test: 
#  stage: test 
#  image: existdb/existdb:release 
#  dependencies:
#    - build  
#  script:
#        - echo "Testing the app"
