#Start developing with CI
services: 
  - existdb 

stages:
  - build 
  - test

build:
  stage: build 
  image:  openjdk:8-jdk-slim
  artifacts:
          paths: 
            - /tmp
  script:
        - echo "Building the app"

test: 
  stage: test 
  image: existdb/existdb:latest 
  dependencies:
    - build  
  script:
        - echo "Testing the app"
